package(default_visibility = ["//visibility:public"])

alias(
    name = "sandbox",
    actual = "//sandbox/sandbox:sandbox",
)

test_suite(
    name = "sandbox_tests",
    tests = [
        "//sandbox/sandbox:sandbox_test",
        "//sandbox/sandbox:config_test",
        "//sandbox/sandbox:fs_test",
        "//sandbox/sandbox:idmap_test",
        "//sandbox/sandbox:network_test",
        "//sandbox/sandbox:utils_test",
        "//sandbox/sandbox:parent_test",
        "//sandbox/sandbox:child_test",
        "//sandbox/sandbox:resources_test",
        "//sandbox/sandbox:security_test",
        "//sandbox/sandbox:sandbox_integration_test",
        "//sandbox/sandbox:sandbox_e2e_test",
        "//sandbox/sandbox:sandbox_privileged_e2e_test",
    ],
)

alias(
    name = "demo",
    actual = "//sandbox/demo:demo",
)

alias(
    name = "demo_precompiled",
    actual = "//sandbox/demo:demo_precompiled",
)

alias(
    name = "demo_precompiled_zipapp",
    actual = "//sandbox/demo:demo_precompiled_zipapp",
)
