package(default_visibility = ["//visibility:public"])

alias(
    name = "demo",
    actual = "//sandbox/demo:demo",
)

alias(
    name = "demo_precompiled",
    actual = "//sandbox/demo:demo_precompiled",
)

alias(
    name = "demo_precompiled_zipapp",
    actual = "//sandbox/demo:demo_precompiled_zipapp",
)
