module(
    name = "study_project",
    version = "0.1.0",
)

bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "rules_pkg", version = "1.2.0")
bazel_dep(name = "rules_python", version = "2.0.2")

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.defaults(python_version = "3.14")
python.toolchain(python_version = "3.14")

typst = use_extension("//tools/typst:extensions.bzl", "typst")
typst.toolchain(version = "0.14.2")
use_repo(typst, "typst_toolchains")

register_toolchains("@typst_toolchains//:all")
