load("@rules_python//python:py_binary.bzl", "py_binary")

py_binary(
    name = "demo",
    srcs = glob(["**/*.py"]),
    main = "main.py",
    precompile = "enabled",
    precompile_optimize_level = 2,
    precompile_source_retention = "omit_source",
    pyc_collection = "include_pyc",
    visibility = ["//sandbox:__subpackages__"],
)
