load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "demo_lib",
    srcs = [
        "main.go",
        "args.go",
    ],
    importpath = "sandbox/demo",
    visibility = ["//visibility:private"],
    deps = [
        "//config",
        "//network",
        "//parent",
        "//child",
        "//common",
        "//utils",
    ],
)

go_binary(
    name = "demo",
    embed = [":demo_lib"],
    visibility = ["//sandbox:__subpackages__"],
)