load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

package(default_visibility = ["//sandbox:__subpackages__"])

go_library(
    name = "common",
    srcs = ["common/common.go"],
    importpath = "sandbox/sandbox/common",
    deps = [":config"],
)

go_library(
    name = "network",
    srcs = glob(["network/*.go"], exclude = ["network/*_test.go"]),
    importpath = "sandbox/sandbox/network",
)

go_library(
    name = "config",
    srcs = glob(["config/*.go"], exclude = ["config/*_test.go"]),
    importpath = "sandbox/sandbox/config",
    deps = [
        ":network",
        "@in_gopkg_yaml_v3//:go_default_library",
    ],
)

go_library(
    name = "fs",
    srcs = glob(["fs/*.go"], exclude = ["fs/*_test.go"]),
    importpath = "sandbox/sandbox/fs",
    deps = [
        ":config",
        "@org_golang_x_sys//unix:go_default_library",
    ],
)

go_library(
    name = "idmap",
    srcs = ["idmap/idmap.go"],
    importpath = "sandbox/sandbox/idmap",
)

go_library(
    name = "diag",
    srcs = ["diag/diag.go"],
    importpath = "sandbox/sandbox/diag",
    deps = [":utils"],
)

go_library(
    name = "resources",
    srcs = glob(["resources/*.go"], exclude = ["resources/*_test.go"]),
    importpath = "sandbox/sandbox/resources",
    deps = [":config"],
)

go_library(
    name = "rootfs",
    srcs = glob(["rootfs/*.go"], exclude = ["rootfs/*_test.go"]),
    importpath = "sandbox/sandbox/rootfs",
    deps = ["@org_golang_x_sys//unix:go_default_library"],
)

go_library(
    name = "security",
    srcs = glob(["security/*.go"], exclude = ["security/*_test.go"]),
    importpath = "sandbox/sandbox/security",
    deps = [
        ":config",
        "@org_golang_x_sys//unix:go_default_library",
    ],
)

go_library(
    name = "utils",
    srcs = ["utils/utils.go"],
    importpath = "sandbox/sandbox/utils",
)

go_library(
    name = "child",
    srcs = glob(["child/*.go"], exclude = ["child/*_test.go"]),
    importpath = "sandbox/sandbox/child",
    deps = [
        ":common",
        ":config",
        ":fs",
        ":network",
        ":resources",
        ":security",
        "@org_golang_x_sys//unix:go_default_library",
    ],
)

go_library(
    name = "parent",
    srcs = glob(["parent/*.go"], exclude = ["parent/*_test.go"]),
    importpath = "sandbox/sandbox/parent",
    deps = [
        ":common",
        ":config",
        ":network",
        ":resources",
        ":rootfs",
        ":security",
    ],
)

go_binary(
    name = "sandbox",
    srcs = ["main.go", "args.go"],
    deps = [
        ":child",
        ":common",
        ":config",
        ":network",
        ":parent",
        ":security",
        ":utils",
        "@org_golang_x_sys//unix:go_default_library",
    ],
)

go_binary(
    name = "testprobe",
    srcs = ["testprobe/main.go"],
    deps = ["@org_golang_x_sys//unix:go_default_library"],
)

go_test(
    name = "sandbox_test",
    srcs = ["main.go", "args.go", "main_test.go"],
    importpath = "sandbox/sandbox",
    deps = [
        ":child",
        ":common",
        ":config",
        ":network",
        ":parent",
        ":security",
        ":utils",
        "@org_golang_x_sys//unix:go_default_library",
    ],
)

go_test(
    name = "config_test",
    srcs = glob(["config/*.go"]),
    importpath = "sandbox/sandbox/config",
    deps = [
        ":network",
        "@in_gopkg_yaml_v3//:go_default_library",
    ],
)

go_test(
    name = "common_test",
    srcs = glob(["common/*.go"]),
    importpath = "sandbox/sandbox/common",
    deps = [":config"],
)

go_test(
    name = "fs_test",
    srcs = glob(["fs/*.go"]),
    importpath = "sandbox/sandbox/fs",
    deps = [
        ":config",
        "@org_golang_x_sys//unix:go_default_library",
    ],
)

go_test(
    name = "idmap_test",
    srcs = ["idmap/idmap.go", "idmap/idmap_test.go"],
    importpath = "sandbox/sandbox/idmap",
    deps = [":fs"],
)

go_test(
    name = "network_test",
    srcs = glob(["network/*.go"]),
    importpath = "sandbox/sandbox/network",
)

go_test(
    name = "utils_test",
    srcs = glob(["utils/*.go"]),
    importpath = "sandbox/sandbox/utils",
)

go_test(
    name = "parent_test",
    srcs = glob(["parent/*.go"]),
    importpath = "sandbox/sandbox/parent",
    deps = [
        ":common",
        ":config",
        ":network",
        ":resources",
        ":rootfs",
        ":security",
    ],
)

go_test(
    name = "resources_test",
    srcs = glob(["resources/*.go"]),
    importpath = "sandbox/sandbox/resources",
    deps = [":config"],
)

go_test(
    name = "rootfs_test",
    srcs = glob(["rootfs/*.go"]),
    importpath = "sandbox/sandbox/rootfs",
    deps = ["@org_golang_x_sys//unix:go_default_library"],
)

go_test(
    name = "security_test",
    srcs = glob(["security/*.go"]),
    importpath = "sandbox/sandbox/security",
    deps = [
        ":config",
        "@org_golang_x_sys//unix:go_default_library",
    ],
)

go_test(
    name = "sandbox_integration_test",
    srcs = [
        "main.go",
        "args.go",
        "sandbox_integration_test.go",
        "sandbox_test_helpers_test.go",
    ],
    data = [":sandbox", ":testprobe"],
    importpath = "sandbox/sandbox",
    deps = [
        ":child",
        ":common",
        ":config",
        ":network",
        ":parent",
        ":security",
        ":utils",
        "@org_golang_x_sys//unix:go_default_library",
    ],
)

go_test(
    name = "sandbox_e2e_test",
    srcs = [
        "main.go",
        "args.go",
        "sandbox_e2e_test.go",
        "sandbox_managed_rootfs_e2e_test.go",
        "sandbox_security_e2e_test.go",
        "sandbox_test_helpers_test.go",
    ],
    data = [":sandbox", ":testprobe"],
    importpath = "sandbox/sandbox",
    deps = [
        ":child",
        ":common",
        ":config",
        ":network",
        ":parent",
        ":security",
        ":utils",
        "@org_golang_x_sys//unix:go_default_library",
    ],
)

go_test(
    name = "sandbox_privileged_e2e_test",
    srcs = [
        "main.go",
        "args.go",
        "sandbox_bridge_e2e_test.go",
        "sandbox_e2e_test.go",
        "sandbox_test_helpers_test.go",
    ],
    data = [":sandbox", ":testprobe"],
    importpath = "sandbox/sandbox",
    deps = [
        ":child",
        ":common",
        ":config",
        ":network",
        ":parent",
        ":security",
        ":utils",
        "@org_golang_x_sys//unix:go_default_library",
    ],
)
