load("//tools/typst:typst_pdf.bzl", "typst_pdf")

typst_pdf(
    name = "Phase_1__Problem_Identification_and_Planning",
    srcs = glob([
        "Phase_1__Problem_Identification_and_Planning/**",
    ]),
    main = "Phase_1__Problem_Identification_and_Planning/main.typ",
    visibility = ["//visibility:public"],
)

typst_pdf(
    name = "Phase_2__Design_and_Proof_of_Concept",
    srcs = glob([
        "Phase_2__Design_and_Proof_of_Concept/**",
    ]),
    main = "Phase_2__Design_and_Proof_of_Concept/main.typ",
    visibility = ["//visibility:public"],
)

typst_pdf(
    name = "Phase_3__Implementation_Readiness_and_Validation",
    srcs = glob([
        "Phase_3__Implementation_Readiness_and_Validation/**",
    ]),
    main = "Phase_3__Implementation_Readiness_and_Validation/main.typ",
    visibility = ["//visibility:public"],
)
